name: qcportal
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - requests
  - pydantic >=0.30.1
  - pyyaml >=5.1
  - plotly
  - py3dmol

# Test depends
  - pytest
  - pytest-cov
  - codecov

# QCArchive includes
  - qcelemental>=0.5.0
